# Generated by Django 5.0.3 on 2024-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
