# Generated by Django 5.0.3 on 2024-03-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fig', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
