# Generated by Django 5.0.3 on 2024-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fig', '0005_file_alter_profile_user_alter_profile_figma_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='figma_file',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
