# Generated by Django 5.0.3 on 2024-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fig', '0007_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figma_file', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='figma_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='figma_file',
            field=models.ManyToManyField(to='fig.files'),
        ),
    ]
